version: "3.5"

services:
  api01: &api
    image: jxnatan7/rinha_nestjs:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "220mb"

  api02:
    <<: *api 
    hostname: api02
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "100MB"
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
