version: '3.8'

services:
  rinha:
    container_name: rinha
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    driver: bridge
